#ifndef DEF_SHADOW_LABYRINTH_H
#define DEF_SHADOW_LABYRINTH_H
#define DATA_AMBASSADORHELLMAWEVENT 1
#define DATA_BLACKHEARTTHEINCITEREVENT 2
#define DATA_GRANDMASTERVORPIL 3
#define DATA_GRANDMASTERVORPILEVENT 4
#define DATA_MURMUREVENT 5
#endif
