# Makefile.in generated by automake 1.9.6 from Makefile.am.
# src/bindings/ScriptDev2/Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005  Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



# Copyright (C) 2005 MaNGOS <http://www.mangosproject.org/>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

srcdir = .
top_srcdir = ../../..

pkgdatadir = $(datadir)/mangos
pkgincludedir = $(includedir)/mangos
top_builddir = ../../..
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
INSTALL = /usr/bin/install -c
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = i686-pc-linux-gnu
host_triplet = i686-pc-linux-gnu
subdir = src/bindings/ScriptDev2
DIST_COMMON = $(srcdir)/Makefile.am $(srcdir)/Makefile.in
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = $(top_builddir)/config.h
CONFIG_CLEAN_FILES =
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = `echo $$p | sed -e 's|^.*/||'`;
am__installdirs = "$(DESTDIR)$(libdir)"
libLTLIBRARIES_INSTALL = $(INSTALL)
LTLIBRARIES = $(lib_LTLIBRARIES)
libMaNGOSScript_la_DEPENDENCIES =
am_libMaNGOSScript_la_OBJECTS = system.lo ScriptMgr.lo \
	sc_boss_onyxia.lo sc_custom_example.lo sc_generic_caster.lo \
	sc_generic_melee.lo sc_kobold.lo sc_guard_bluffwatcher.lo \
	sc_guard_contested.lo sc_guard_darnassus.lo \
	sc_guard_dunmorogh.lo sc_guard_durotar.lo \
	sc_guard_elwynnforest.lo sc_guard_ironforge.lo \
	sc_guard_mulgore.lo sc_guard_orgrimmar.lo \
	sc_guard_stormwind.lo sc_guard_teldrassil.lo \
	sc_guard_tirisfal.lo sc_guard_undercity.lo sc_honor_vendor.lo \
	sc_marshal_mcbride.lo sc_silas_darkmoon.lo \
	sc_silva_filnaveth.lo sc_skorn_whitecloud.lo \
	sc_battlemaster.lo sc_guildmaster.lo sc_travelmaster.lo \
	sc_default.lo sc_defines.lo
libMaNGOSScript_la_OBJECTS = $(am_libMaNGOSScript_la_OBJECTS)
DEFAULT_INCLUDES = -I. -I$(srcdir) -I$(top_builddir)
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) --tag=CXX --mode=link $(CXXLD) $(AM_CXXFLAGS) \
	$(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --tag=CC --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
SOURCES = $(libMaNGOSScript_la_SOURCES)
DIST_SOURCES = $(libMaNGOSScript_la_SOURCES)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
pkglibdir = $(libdir)
ACLOCAL = ${SHELL} /home/virnik/mangos/missing --run aclocal-1.9
ALLOCA = 
AMDEP_FALSE = #
AMDEP_TRUE = 
AMTAR = ${SHELL} /home/virnik/mangos/missing --run tar
AR = ar
AUTOCONF = ${SHELL} /home/virnik/mangos/missing --run autoconf
AUTOHEADER = ${SHELL} /home/virnik/mangos/missing --run autoheader
AUTOMAKE = ${SHELL} /home/virnik/mangos/missing --run automake-1.9
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
COMPILER_OPTIONS =  -g -O2
CPP = gcc -E
CPPFLAGS = 
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
ECHO = echo
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = grep -E
EXEEXT = 
EXTRA_COMPILER_OPTIONS = 
EXTRA_LINKER_OPTIONS = 
F77 = f95
FFLAGS = -g -O2
INCLUDES = -I/usr/include/mysql -I/usr/local/include/mysql  -I$(srcdir) -I$(srcdir)/../../../dep/include \
	-I$(srcdir)/../../shared -I$(srcdir)/../../framework \
	-I$(srcdir)/../../bindings/ScriptDev2/scripts
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = ${SHELL} $(install_sh) -c -s
LDFLAGS = -L/usr/lib/mysql -L/usr/local/lib/mysql 
LIBOBJS = 
LIBS = -lssl -lmysqlclient_r -lz -lpthread 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LINKER_OPTIONS =  -L/usr/lib/mysql -L/usr/local/lib/mysql 
LN_S = ln -s
LTLIBOBJS = 
LTMS_AGE = 0
LTMS_CURRENT = 0
LTMS_RELEASE = 0.2.0
LTMS_REVISION = 2
LT_AGE = 2
LT_CURRENT = 2
LT_RELEASE = 2.3.2
LT_REVISION = 3
MAINT = #
MAINTAINER_MODE_FALSE = 
MAINTAINER_MODE_TRUE = #
MAKEINFO = ${SHELL} /home/virnik/mangos/missing --run makeinfo
MANGOSD_CONFIG = /usr/local/games/WoW/etc/mangosd.conf
MANGOSD_CONFIGDIR = /usr/local/games/WoW/etc
MANGOSD_DATA = /usr/local/games/WoW/mangos
MANGOSD_ENABLE_CLI = no
MANGOSD_ENABLE_RA = no
MYSQL_INCLUDES = -I/usr/include/mysql -I/usr/local/include/mysql
MYSQL_LDFLAGS = -L/usr/lib/mysql -L/usr/local/lib/mysql
OBJEXT = o
OPENSSL_INCLUDES = 
OPENSSL_LDFLAGS = 
PACKAGE = mangos
PACKAGE_BUGREPORT = http://www.mangosproject.org/
PACKAGE_NAME = MaNGOS
PACKAGE_STRING = MaNGOS 0.6-SVN
PACKAGE_TARNAME = mangos
PACKAGE_VERSION = 0.6-SVN
PATH_SEPARATOR = :
RANLIB = ranlib
REALMD_CONFIG = /usr/local/games/WoW/etc/realmd.conf
REALMD_CONFIGDIR = /usr/local/games/WoW/etc
SED = /bin/sed
SET_MAKE = 
SHELL = /bin/sh
STRIP = strip
VERSION = 0.6-SVN
WITH_APIDOCS = 1
WITH_APIDOCS_TARGET = apidocs
WITH_PYTHON_SUBDIR = python
WITH_PYTHON_SUBPACKAGE = 1
WITH_PYTHON_VERSION = 2.4
__DOXYGEN = /usr/bin/doxygen
__PYTHON = /usr/bin/python
ac_ct_AR = ar
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_F77 = f95
ac_ct_RANLIB = ranlib
ac_ct_STRIP = strip
am__fastdepCC_FALSE = #
am__fastdepCC_TRUE = 
am__fastdepCXX_FALSE = #
am__fastdepCXX_TRUE = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build = i686-pc-linux-gnu
build_alias = 
build_cpu = i686
build_os = linux-gnu
build_vendor = pc
datadir = /usr/local/games/WoW
exec_prefix = ${prefix}
host = i686-pc-linux-gnu
host_alias = 
host_cpu = i686
host_os = linux-gnu
host_vendor = pc
includedir = ${prefix}/include
infodir = ${prefix}/info
install_sh = /home/virnik/mangos/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localstatedir = ${prefix}/var
mandir = ${prefix}/man
mkdir_p = mkdir -p --
oldincludedir = /usr/include
prefix = /usr/local/games/WoW
program_transform_name = s,x,x,
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
sysconfdir = /usr/local/games/WoW/etc
target_alias = 
AM_CXXFLAGS =  -g -O2 
lib_LTLIBRARIES = libMaNGOSScript.la
libMaNGOSScript_la_LIBADD =  -L/usr/lib/mysql -L/usr/local/lib/mysql  
libMaNGOSScript_la_LDFLAGS = \
    -release $(LTMS_RELEASE)\
    -version-info $(LTMS_CURRENT):$(LTMS_REVISION):$(LTMS_AGE)

LIBADD =  -L/usr/lib/mysql -L/usr/local/lib/mysql  
libMaNGOSScript_la_SOURCES = \
    system.cpp \
    config.h \
    ScriptMgr.h \
    ScriptMgr.cpp \
    scripts/boss/sc_boss_onyxia.cpp \
    scripts/custom/sc_custom_example.cpp \
    scripts/creature/sc_generic_caster.cpp \
    scripts/creature/sc_generic_melee.cpp \
    scripts/creature/sc_kobold.cpp \
    scripts/guard/sc_guard_bluffwatcher.cpp \
    scripts/guard/sc_guard_contested.cpp \
    scripts/guard/sc_guard_darnassus.cpp \
    scripts/guard/sc_guard_dunmorogh.cpp \
    scripts/guard/sc_guard_durotar.cpp \
    scripts/guard/sc_guard_elwynnforest.cpp \
    scripts/guard/sc_guard_ironforge.cpp \
    scripts/guard/sc_guard_mulgore.cpp \
    scripts/guard/sc_guard_orgrimmar.cpp \
    scripts/guard/sc_guard_stormwind.cpp \
    scripts/guard/sc_guard_teldrassil.cpp \
    scripts/guard/sc_guard_tirisfal.cpp \
    scripts/guard/sc_guard_undercity.cpp \
    scripts/honor/sc_honor_vendor.cpp \
    scripts/npc/sc_marshal_mcbride.cpp \
    scripts/npc/sc_silas_darkmoon.cpp \
    scripts/npc/sc_silva_filnaveth.cpp \
    scripts/npc/sc_skorn_whitecloud.cpp \
    scripts/servers/sc_battlemaster.cpp \
    scripts/servers/sc_guildmaster.cpp \
    scripts/servers/sc_travelmaster.cpp \
    scripts/sc_default.cpp \
    scripts/sc_defines.cpp \
    scripts/sc_defines.h

all: all-am

.SUFFIXES:
.SUFFIXES: .cpp .lo .o .obj
$(srcdir)/Makefile.in: # $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu  src/bindings/ScriptDev2/Makefile'; \
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --gnu  src/bindings/ScriptDev2/Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh

$(top_srcdir)/configure: # $(am__configure_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(ACLOCAL_M4): # $(am__aclocal_m4_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
install-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	test -z "$(libdir)" || $(mkdir_p) "$(DESTDIR)$(libdir)"
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    f=$(am__strip_dir) \
	    echo " $(LIBTOOL) --mode=install $(libLTLIBRARIES_INSTALL) $(INSTALL_STRIP_FLAG) '$$p' '$(DESTDIR)$(libdir)/$$f'"; \
	    $(LIBTOOL) --mode=install $(libLTLIBRARIES_INSTALL) $(INSTALL_STRIP_FLAG) "$$p" "$(DESTDIR)$(libdir)/$$f"; \
	  else :; fi; \
	done

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@set -x; list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  p=$(am__strip_dir) \
	  echo " $(LIBTOOL) --mode=uninstall rm -f '$(DESTDIR)$(libdir)/$$p'"; \
	  $(LIBTOOL) --mode=uninstall rm -f "$(DESTDIR)$(libdir)/$$p"; \
	done

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  dir="`echo $$p | sed -e 's|/[^/]*$$||'`"; \
	  test "$$dir" != "$$p" || dir=.; \
	  echo "rm -f \"$${dir}/so_locations\""; \
	  rm -f "$${dir}/so_locations"; \
	done
libMaNGOSScript.la: $(libMaNGOSScript_la_OBJECTS) $(libMaNGOSScript_la_DEPENDENCIES) 
	$(CXXLINK) -rpath $(libdir) $(libMaNGOSScript_la_LDFLAGS) $(libMaNGOSScript_la_OBJECTS) $(libMaNGOSScript_la_LIBADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/ScriptMgr.Plo
include ./$(DEPDIR)/sc_battlemaster.Plo
include ./$(DEPDIR)/sc_boss_onyxia.Plo
include ./$(DEPDIR)/sc_custom_example.Plo
include ./$(DEPDIR)/sc_default.Plo
include ./$(DEPDIR)/sc_defines.Plo
include ./$(DEPDIR)/sc_generic_caster.Plo
include ./$(DEPDIR)/sc_generic_melee.Plo
include ./$(DEPDIR)/sc_guard_bluffwatcher.Plo
include ./$(DEPDIR)/sc_guard_contested.Plo
include ./$(DEPDIR)/sc_guard_darnassus.Plo
include ./$(DEPDIR)/sc_guard_dunmorogh.Plo
include ./$(DEPDIR)/sc_guard_durotar.Plo
include ./$(DEPDIR)/sc_guard_elwynnforest.Plo
include ./$(DEPDIR)/sc_guard_ironforge.Plo
include ./$(DEPDIR)/sc_guard_mulgore.Plo
include ./$(DEPDIR)/sc_guard_orgrimmar.Plo
include ./$(DEPDIR)/sc_guard_stormwind.Plo
include ./$(DEPDIR)/sc_guard_teldrassil.Plo
include ./$(DEPDIR)/sc_guard_tirisfal.Plo
include ./$(DEPDIR)/sc_guard_undercity.Plo
include ./$(DEPDIR)/sc_guildmaster.Plo
include ./$(DEPDIR)/sc_honor_vendor.Plo
include ./$(DEPDIR)/sc_kobold.Plo
include ./$(DEPDIR)/sc_marshal_mcbride.Plo
include ./$(DEPDIR)/sc_silas_darkmoon.Plo
include ./$(DEPDIR)/sc_silva_filnaveth.Plo
include ./$(DEPDIR)/sc_skorn_whitecloud.Plo
include ./$(DEPDIR)/sc_travelmaster.Plo
include ./$(DEPDIR)/system.Plo

.cpp.o:
	if $(CXXCOMPILE) -MT $@ -MD -MP -MF "$(DEPDIR)/$*.Tpo" -c -o $@ $<; \
	then mv -f "$(DEPDIR)/$*.Tpo" "$(DEPDIR)/$*.Po"; else rm -f "$(DEPDIR)/$*.Tpo"; exit 1; fi
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	if $(CXXCOMPILE) -MT $@ -MD -MP -MF "$(DEPDIR)/$*.Tpo" -c -o $@ `$(CYGPATH_W) '$<'`; \
	then mv -f "$(DEPDIR)/$*.Tpo" "$(DEPDIR)/$*.Po"; else rm -f "$(DEPDIR)/$*.Tpo"; exit 1; fi
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.cpp.lo:
	if $(LTCXXCOMPILE) -MT $@ -MD -MP -MF "$(DEPDIR)/$*.Tpo" -c -o $@ $<; \
	then mv -f "$(DEPDIR)/$*.Tpo" "$(DEPDIR)/$*.Plo"; else rm -f "$(DEPDIR)/$*.Tpo"; exit 1; fi
#	source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LTCXXCOMPILE) -c -o $@ $<

sc_boss_onyxia.lo: scripts/boss/sc_boss_onyxia.cpp
	if $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT sc_boss_onyxia.lo -MD -MP -MF "$(DEPDIR)/sc_boss_onyxia.Tpo" -c -o sc_boss_onyxia.lo `test -f 'scripts/boss/sc_boss_onyxia.cpp' || echo '$(srcdir)/'`scripts/boss/sc_boss_onyxia.cpp; \
	then mv -f "$(DEPDIR)/sc_boss_onyxia.Tpo" "$(DEPDIR)/sc_boss_onyxia.Plo"; else rm -f "$(DEPDIR)/sc_boss_onyxia.Tpo"; exit 1; fi
#	source='scripts/boss/sc_boss_onyxia.cpp' object='sc_boss_onyxia.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o sc_boss_onyxia.lo `test -f 'scripts/boss/sc_boss_onyxia.cpp' || echo '$(srcdir)/'`scripts/boss/sc_boss_onyxia.cpp

sc_custom_example.lo: scripts/custom/sc_custom_example.cpp
	if $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT sc_custom_example.lo -MD -MP -MF "$(DEPDIR)/sc_custom_example.Tpo" -c -o sc_custom_example.lo `test -f 'scripts/custom/sc_custom_example.cpp' || echo '$(srcdir)/'`scripts/custom/sc_custom_example.cpp; \
	then mv -f "$(DEPDIR)/sc_custom_example.Tpo" "$(DEPDIR)/sc_custom_example.Plo"; else rm -f "$(DEPDIR)/sc_custom_example.Tpo"; exit 1; fi
#	source='scripts/custom/sc_custom_example.cpp' object='sc_custom_example.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o sc_custom_example.lo `test -f 'scripts/custom/sc_custom_example.cpp' || echo '$(srcdir)/'`scripts/custom/sc_custom_example.cpp

sc_generic_caster.lo: scripts/creature/sc_generic_caster.cpp
	if $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT sc_generic_caster.lo -MD -MP -MF "$(DEPDIR)/sc_generic_caster.Tpo" -c -o sc_generic_caster.lo `test -f 'scripts/creature/sc_generic_caster.cpp' || echo '$(srcdir)/'`scripts/creature/sc_generic_caster.cpp; \
	then mv -f "$(DEPDIR)/sc_generic_caster.Tpo" "$(DEPDIR)/sc_generic_caster.Plo"; else rm -f "$(DEPDIR)/sc_generic_caster.Tpo"; exit 1; fi
#	source='scripts/creature/sc_generic_caster.cpp' object='sc_generic_caster.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o sc_generic_caster.lo `test -f 'scripts/creature/sc_generic_caster.cpp' || echo '$(srcdir)/'`scripts/creature/sc_generic_caster.cpp

sc_generic_melee.lo: scripts/creature/sc_generic_melee.cpp
	if $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT sc_generic_melee.lo -MD -MP -MF "$(DEPDIR)/sc_generic_melee.Tpo" -c -o sc_generic_melee.lo `test -f 'scripts/creature/sc_generic_melee.cpp' || echo '$(srcdir)/'`scripts/creature/sc_generic_melee.cpp; \
	then mv -f "$(DEPDIR)/sc_generic_melee.Tpo" "$(DEPDIR)/sc_generic_melee.Plo"; else rm -f "$(DEPDIR)/sc_generic_melee.Tpo"; exit 1; fi
#	source='scripts/creature/sc_generic_melee.cpp' object='sc_generic_melee.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o sc_generic_melee.lo `test -f 'scripts/creature/sc_generic_melee.cpp' || echo '$(srcdir)/'`scripts/creature/sc_generic_melee.cpp

sc_kobold.lo: scripts/creature/sc_kobold.cpp
	if $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT sc_kobold.lo -MD -MP -MF "$(DEPDIR)/sc_kobold.Tpo" -c -o sc_kobold.lo `test -f 'scripts/creature/sc_kobold.cpp' || echo '$(srcdir)/'`scripts/creature/sc_kobold.cpp; \
	then mv -f "$(DEPDIR)/sc_kobold.Tpo" "$(DEPDIR)/sc_kobold.Plo"; else rm -f "$(DEPDIR)/sc_kobold.Tpo"; exit 1; fi
#	source='scripts/creature/sc_kobold.cpp' object='sc_kobold.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o sc_kobold.lo `test -f 'scripts/creature/sc_kobold.cpp' || echo '$(srcdir)/'`scripts/creature/sc_kobold.cpp

sc_guard_bluffwatcher.lo: scripts/guard/sc_guard_bluffwatcher.cpp
	if $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT sc_guard_bluffwatcher.lo -MD -MP -MF "$(DEPDIR)/sc_guard_bluffwatcher.Tpo" -c -o sc_guard_bluffwatcher.lo `test -f 'scripts/guard/sc_guard_bluffwatcher.cpp' || echo '$(srcdir)/'`scripts/guard/sc_guard_bluffwatcher.cpp; \
	then mv -f "$(DEPDIR)/sc_guard_bluffwatcher.Tpo" "$(DEPDIR)/sc_guard_bluffwatcher.Plo"; else rm -f "$(DEPDIR)/sc_guard_bluffwatcher.Tpo"; exit 1; fi
#	source='scripts/guard/sc_guard_bluffwatcher.cpp' object='sc_guard_bluffwatcher.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o sc_guard_bluffwatcher.lo `test -f 'scripts/guard/sc_guard_bluffwatcher.cpp' || echo '$(srcdir)/'`scripts/guard/sc_guard_bluffwatcher.cpp

sc_guard_contested.lo: scripts/guard/sc_guard_contested.cpp
	if $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT sc_guard_contested.lo -MD -MP -MF "$(DEPDIR)/sc_guard_contested.Tpo" -c -o sc_guard_contested.lo `test -f 'scripts/guard/sc_guard_contested.cpp' || echo '$(srcdir)/'`scripts/guard/sc_guard_contested.cpp; \
	then mv -f "$(DEPDIR)/sc_guard_contested.Tpo" "$(DEPDIR)/sc_guard_contested.Plo"; else rm -f "$(DEPDIR)/sc_guard_contested.Tpo"; exit 1; fi
#	source='scripts/guard/sc_guard_contested.cpp' object='sc_guard_contested.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o sc_guard_contested.lo `test -f 'scripts/guard/sc_guard_contested.cpp' || echo '$(srcdir)/'`scripts/guard/sc_guard_contested.cpp

sc_guard_darnassus.lo: scripts/guard/sc_guard_darnassus.cpp
	if $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT sc_guard_darnassus.lo -MD -MP -MF "$(DEPDIR)/sc_guard_darnassus.Tpo" -c -o sc_guard_darnassus.lo `test -f 'scripts/guard/sc_guard_darnassus.cpp' || echo '$(srcdir)/'`scripts/guard/sc_guard_darnassus.cpp; \
	then mv -f "$(DEPDIR)/sc_guard_darnassus.Tpo" "$(DEPDIR)/sc_guard_darnassus.Plo"; else rm -f "$(DEPDIR)/sc_guard_darnassus.Tpo"; exit 1; fi
#	source='scripts/guard/sc_guard_darnassus.cpp' object='sc_guard_darnassus.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o sc_guard_darnassus.lo `test -f 'scripts/guard/sc_guard_darnassus.cpp' || echo '$(srcdir)/'`scripts/guard/sc_guard_darnassus.cpp

sc_guard_dunmorogh.lo: scripts/guard/sc_guard_dunmorogh.cpp
	if $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT sc_guard_dunmorogh.lo -MD -MP -MF "$(DEPDIR)/sc_guard_dunmorogh.Tpo" -c -o sc_guard_dunmorogh.lo `test -f 'scripts/guard/sc_guard_dunmorogh.cpp' || echo '$(srcdir)/'`scripts/guard/sc_guard_dunmorogh.cpp; \
	then mv -f "$(DEPDIR)/sc_guard_dunmorogh.Tpo" "$(DEPDIR)/sc_guard_dunmorogh.Plo"; else rm -f "$(DEPDIR)/sc_guard_dunmorogh.Tpo"; exit 1; fi
#	source='scripts/guard/sc_guard_dunmorogh.cpp' object='sc_guard_dunmorogh.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o sc_guard_dunmorogh.lo `test -f 'scripts/guard/sc_guard_dunmorogh.cpp' || echo '$(srcdir)/'`scripts/guard/sc_guard_dunmorogh.cpp

sc_guard_durotar.lo: scripts/guard/sc_guard_durotar.cpp
	if $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT sc_guard_durotar.lo -MD -MP -MF "$(DEPDIR)/sc_guard_durotar.Tpo" -c -o sc_guard_durotar.lo `test -f 'scripts/guard/sc_guard_durotar.cpp' || echo '$(srcdir)/'`scripts/guard/sc_guard_durotar.cpp; \
	then mv -f "$(DEPDIR)/sc_guard_durotar.Tpo" "$(DEPDIR)/sc_guard_durotar.Plo"; else rm -f "$(DEPDIR)/sc_guard_durotar.Tpo"; exit 1; fi
#	source='scripts/guard/sc_guard_durotar.cpp' object='sc_guard_durotar.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o sc_guard_durotar.lo `test -f 'scripts/guard/sc_guard_durotar.cpp' || echo '$(srcdir)/'`scripts/guard/sc_guard_durotar.cpp

sc_guard_elwynnforest.lo: scripts/guard/sc_guard_elwynnforest.cpp
	if $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT sc_guard_elwynnforest.lo -MD -MP -MF "$(DEPDIR)/sc_guard_elwynnforest.Tpo" -c -o sc_guard_elwynnforest.lo `test -f 'scripts/guard/sc_guard_elwynnforest.cpp' || echo '$(srcdir)/'`scripts/guard/sc_guard_elwynnforest.cpp; \
	then mv -f "$(DEPDIR)/sc_guard_elwynnforest.Tpo" "$(DEPDIR)/sc_guard_elwynnforest.Plo"; else rm -f "$(DEPDIR)/sc_guard_elwynnforest.Tpo"; exit 1; fi
#	source='scripts/guard/sc_guard_elwynnforest.cpp' object='sc_guard_elwynnforest.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o sc_guard_elwynnforest.lo `test -f 'scripts/guard/sc_guard_elwynnforest.cpp' || echo '$(srcdir)/'`scripts/guard/sc_guard_elwynnforest.cpp

sc_guard_ironforge.lo: scripts/guard/sc_guard_ironforge.cpp
	if $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT sc_guard_ironforge.lo -MD -MP -MF "$(DEPDIR)/sc_guard_ironforge.Tpo" -c -o sc_guard_ironforge.lo `test -f 'scripts/guard/sc_guard_ironforge.cpp' || echo '$(srcdir)/'`scripts/guard/sc_guard_ironforge.cpp; \
	then mv -f "$(DEPDIR)/sc_guard_ironforge.Tpo" "$(DEPDIR)/sc_guard_ironforge.Plo"; else rm -f "$(DEPDIR)/sc_guard_ironforge.Tpo"; exit 1; fi
#	source='scripts/guard/sc_guard_ironforge.cpp' object='sc_guard_ironforge.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o sc_guard_ironforge.lo `test -f 'scripts/guard/sc_guard_ironforge.cpp' || echo '$(srcdir)/'`scripts/guard/sc_guard_ironforge.cpp

sc_guard_mulgore.lo: scripts/guard/sc_guard_mulgore.cpp
	if $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT sc_guard_mulgore.lo -MD -MP -MF "$(DEPDIR)/sc_guard_mulgore.Tpo" -c -o sc_guard_mulgore.lo `test -f 'scripts/guard/sc_guard_mulgore.cpp' || echo '$(srcdir)/'`scripts/guard/sc_guard_mulgore.cpp; \
	then mv -f "$(DEPDIR)/sc_guard_mulgore.Tpo" "$(DEPDIR)/sc_guard_mulgore.Plo"; else rm -f "$(DEPDIR)/sc_guard_mulgore.Tpo"; exit 1; fi
#	source='scripts/guard/sc_guard_mulgore.cpp' object='sc_guard_mulgore.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o sc_guard_mulgore.lo `test -f 'scripts/guard/sc_guard_mulgore.cpp' || echo '$(srcdir)/'`scripts/guard/sc_guard_mulgore.cpp

sc_guard_orgrimmar.lo: scripts/guard/sc_guard_orgrimmar.cpp
	if $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT sc_guard_orgrimmar.lo -MD -MP -MF "$(DEPDIR)/sc_guard_orgrimmar.Tpo" -c -o sc_guard_orgrimmar.lo `test -f 'scripts/guard/sc_guard_orgrimmar.cpp' || echo '$(srcdir)/'`scripts/guard/sc_guard_orgrimmar.cpp; \
	then mv -f "$(DEPDIR)/sc_guard_orgrimmar.Tpo" "$(DEPDIR)/sc_guard_orgrimmar.Plo"; else rm -f "$(DEPDIR)/sc_guard_orgrimmar.Tpo"; exit 1; fi
#	source='scripts/guard/sc_guard_orgrimmar.cpp' object='sc_guard_orgrimmar.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o sc_guard_orgrimmar.lo `test -f 'scripts/guard/sc_guard_orgrimmar.cpp' || echo '$(srcdir)/'`scripts/guard/sc_guard_orgrimmar.cpp

sc_guard_stormwind.lo: scripts/guard/sc_guard_stormwind.cpp
	if $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT sc_guard_stormwind.lo -MD -MP -MF "$(DEPDIR)/sc_guard_stormwind.Tpo" -c -o sc_guard_stormwind.lo `test -f 'scripts/guard/sc_guard_stormwind.cpp' || echo '$(srcdir)/'`scripts/guard/sc_guard_stormwind.cpp; \
	then mv -f "$(DEPDIR)/sc_guard_stormwind.Tpo" "$(DEPDIR)/sc_guard_stormwind.Plo"; else rm -f "$(DEPDIR)/sc_guard_stormwind.Tpo"; exit 1; fi
#	source='scripts/guard/sc_guard_stormwind.cpp' object='sc_guard_stormwind.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o sc_guard_stormwind.lo `test -f 'scripts/guard/sc_guard_stormwind.cpp' || echo '$(srcdir)/'`scripts/guard/sc_guard_stormwind.cpp

sc_guard_teldrassil.lo: scripts/guard/sc_guard_teldrassil.cpp
	if $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT sc_guard_teldrassil.lo -MD -MP -MF "$(DEPDIR)/sc_guard_teldrassil.Tpo" -c -o sc_guard_teldrassil.lo `test -f 'scripts/guard/sc_guard_teldrassil.cpp' || echo '$(srcdir)/'`scripts/guard/sc_guard_teldrassil.cpp; \
	then mv -f "$(DEPDIR)/sc_guard_teldrassil.Tpo" "$(DEPDIR)/sc_guard_teldrassil.Plo"; else rm -f "$(DEPDIR)/sc_guard_teldrassil.Tpo"; exit 1; fi
#	source='scripts/guard/sc_guard_teldrassil.cpp' object='sc_guard_teldrassil.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o sc_guard_teldrassil.lo `test -f 'scripts/guard/sc_guard_teldrassil.cpp' || echo '$(srcdir)/'`scripts/guard/sc_guard_teldrassil.cpp

sc_guard_tirisfal.lo: scripts/guard/sc_guard_tirisfal.cpp
	if $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT sc_guard_tirisfal.lo -MD -MP -MF "$(DEPDIR)/sc_guard_tirisfal.Tpo" -c -o sc_guard_tirisfal.lo `test -f 'scripts/guard/sc_guard_tirisfal.cpp' || echo '$(srcdir)/'`scripts/guard/sc_guard_tirisfal.cpp; \
	then mv -f "$(DEPDIR)/sc_guard_tirisfal.Tpo" "$(DEPDIR)/sc_guard_tirisfal.Plo"; else rm -f "$(DEPDIR)/sc_guard_tirisfal.Tpo"; exit 1; fi
#	source='scripts/guard/sc_guard_tirisfal.cpp' object='sc_guard_tirisfal.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o sc_guard_tirisfal.lo `test -f 'scripts/guard/sc_guard_tirisfal.cpp' || echo '$(srcdir)/'`scripts/guard/sc_guard_tirisfal.cpp

sc_guard_undercity.lo: scripts/guard/sc_guard_undercity.cpp
	if $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT sc_guard_undercity.lo -MD -MP -MF "$(DEPDIR)/sc_guard_undercity.Tpo" -c -o sc_guard_undercity.lo `test -f 'scripts/guard/sc_guard_undercity.cpp' || echo '$(srcdir)/'`scripts/guard/sc_guard_undercity.cpp; \
	then mv -f "$(DEPDIR)/sc_guard_undercity.Tpo" "$(DEPDIR)/sc_guard_undercity.Plo"; else rm -f "$(DEPDIR)/sc_guard_undercity.Tpo"; exit 1; fi
#	source='scripts/guard/sc_guard_undercity.cpp' object='sc_guard_undercity.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o sc_guard_undercity.lo `test -f 'scripts/guard/sc_guard_undercity.cpp' || echo '$(srcdir)/'`scripts/guard/sc_guard_undercity.cpp

sc_honor_vendor.lo: scripts/honor/sc_honor_vendor.cpp
	if $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT sc_honor_vendor.lo -MD -MP -MF "$(DEPDIR)/sc_honor_vendor.Tpo" -c -o sc_honor_vendor.lo `test -f 'scripts/honor/sc_honor_vendor.cpp' || echo '$(srcdir)/'`scripts/honor/sc_honor_vendor.cpp; \
	then mv -f "$(DEPDIR)/sc_honor_vendor.Tpo" "$(DEPDIR)/sc_honor_vendor.Plo"; else rm -f "$(DEPDIR)/sc_honor_vendor.Tpo"; exit 1; fi
#	source='scripts/honor/sc_honor_vendor.cpp' object='sc_honor_vendor.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o sc_honor_vendor.lo `test -f 'scripts/honor/sc_honor_vendor.cpp' || echo '$(srcdir)/'`scripts/honor/sc_honor_vendor.cpp

sc_marshal_mcbride.lo: scripts/npc/sc_marshal_mcbride.cpp
	if $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT sc_marshal_mcbride.lo -MD -MP -MF "$(DEPDIR)/sc_marshal_mcbride.Tpo" -c -o sc_marshal_mcbride.lo `test -f 'scripts/npc/sc_marshal_mcbride.cpp' || echo '$(srcdir)/'`scripts/npc/sc_marshal_mcbride.cpp; \
	then mv -f "$(DEPDIR)/sc_marshal_mcbride.Tpo" "$(DEPDIR)/sc_marshal_mcbride.Plo"; else rm -f "$(DEPDIR)/sc_marshal_mcbride.Tpo"; exit 1; fi
#	source='scripts/npc/sc_marshal_mcbride.cpp' object='sc_marshal_mcbride.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o sc_marshal_mcbride.lo `test -f 'scripts/npc/sc_marshal_mcbride.cpp' || echo '$(srcdir)/'`scripts/npc/sc_marshal_mcbride.cpp

sc_silas_darkmoon.lo: scripts/npc/sc_silas_darkmoon.cpp
	if $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT sc_silas_darkmoon.lo -MD -MP -MF "$(DEPDIR)/sc_silas_darkmoon.Tpo" -c -o sc_silas_darkmoon.lo `test -f 'scripts/npc/sc_silas_darkmoon.cpp' || echo '$(srcdir)/'`scripts/npc/sc_silas_darkmoon.cpp; \
	then mv -f "$(DEPDIR)/sc_silas_darkmoon.Tpo" "$(DEPDIR)/sc_silas_darkmoon.Plo"; else rm -f "$(DEPDIR)/sc_silas_darkmoon.Tpo"; exit 1; fi
#	source='scripts/npc/sc_silas_darkmoon.cpp' object='sc_silas_darkmoon.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o sc_silas_darkmoon.lo `test -f 'scripts/npc/sc_silas_darkmoon.cpp' || echo '$(srcdir)/'`scripts/npc/sc_silas_darkmoon.cpp

sc_silva_filnaveth.lo: scripts/npc/sc_silva_filnaveth.cpp
	if $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT sc_silva_filnaveth.lo -MD -MP -MF "$(DEPDIR)/sc_silva_filnaveth.Tpo" -c -o sc_silva_filnaveth.lo `test -f 'scripts/npc/sc_silva_filnaveth.cpp' || echo '$(srcdir)/'`scripts/npc/sc_silva_filnaveth.cpp; \
	then mv -f "$(DEPDIR)/sc_silva_filnaveth.Tpo" "$(DEPDIR)/sc_silva_filnaveth.Plo"; else rm -f "$(DEPDIR)/sc_silva_filnaveth.Tpo"; exit 1; fi
#	source='scripts/npc/sc_silva_filnaveth.cpp' object='sc_silva_filnaveth.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o sc_silva_filnaveth.lo `test -f 'scripts/npc/sc_silva_filnaveth.cpp' || echo '$(srcdir)/'`scripts/npc/sc_silva_filnaveth.cpp

sc_skorn_whitecloud.lo: scripts/npc/sc_skorn_whitecloud.cpp
	if $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT sc_skorn_whitecloud.lo -MD -MP -MF "$(DEPDIR)/sc_skorn_whitecloud.Tpo" -c -o sc_skorn_whitecloud.lo `test -f 'scripts/npc/sc_skorn_whitecloud.cpp' || echo '$(srcdir)/'`scripts/npc/sc_skorn_whitecloud.cpp; \
	then mv -f "$(DEPDIR)/sc_skorn_whitecloud.Tpo" "$(DEPDIR)/sc_skorn_whitecloud.Plo"; else rm -f "$(DEPDIR)/sc_skorn_whitecloud.Tpo"; exit 1; fi
#	source='scripts/npc/sc_skorn_whitecloud.cpp' object='sc_skorn_whitecloud.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o sc_skorn_whitecloud.lo `test -f 'scripts/npc/sc_skorn_whitecloud.cpp' || echo '$(srcdir)/'`scripts/npc/sc_skorn_whitecloud.cpp

sc_battlemaster.lo: scripts/servers/sc_battlemaster.cpp
	if $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT sc_battlemaster.lo -MD -MP -MF "$(DEPDIR)/sc_battlemaster.Tpo" -c -o sc_battlemaster.lo `test -f 'scripts/servers/sc_battlemaster.cpp' || echo '$(srcdir)/'`scripts/servers/sc_battlemaster.cpp; \
	then mv -f "$(DEPDIR)/sc_battlemaster.Tpo" "$(DEPDIR)/sc_battlemaster.Plo"; else rm -f "$(DEPDIR)/sc_battlemaster.Tpo"; exit 1; fi
#	source='scripts/servers/sc_battlemaster.cpp' object='sc_battlemaster.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o sc_battlemaster.lo `test -f 'scripts/servers/sc_battlemaster.cpp' || echo '$(srcdir)/'`scripts/servers/sc_battlemaster.cpp

sc_guildmaster.lo: scripts/servers/sc_guildmaster.cpp
	if $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT sc_guildmaster.lo -MD -MP -MF "$(DEPDIR)/sc_guildmaster.Tpo" -c -o sc_guildmaster.lo `test -f 'scripts/servers/sc_guildmaster.cpp' || echo '$(srcdir)/'`scripts/servers/sc_guildmaster.cpp; \
	then mv -f "$(DEPDIR)/sc_guildmaster.Tpo" "$(DEPDIR)/sc_guildmaster.Plo"; else rm -f "$(DEPDIR)/sc_guildmaster.Tpo"; exit 1; fi
#	source='scripts/servers/sc_guildmaster.cpp' object='sc_guildmaster.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o sc_guildmaster.lo `test -f 'scripts/servers/sc_guildmaster.cpp' || echo '$(srcdir)/'`scripts/servers/sc_guildmaster.cpp

sc_travelmaster.lo: scripts/servers/sc_travelmaster.cpp
	if $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT sc_travelmaster.lo -MD -MP -MF "$(DEPDIR)/sc_travelmaster.Tpo" -c -o sc_travelmaster.lo `test -f 'scripts/servers/sc_travelmaster.cpp' || echo '$(srcdir)/'`scripts/servers/sc_travelmaster.cpp; \
	then mv -f "$(DEPDIR)/sc_travelmaster.Tpo" "$(DEPDIR)/sc_travelmaster.Plo"; else rm -f "$(DEPDIR)/sc_travelmaster.Tpo"; exit 1; fi
#	source='scripts/servers/sc_travelmaster.cpp' object='sc_travelmaster.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o sc_travelmaster.lo `test -f 'scripts/servers/sc_travelmaster.cpp' || echo '$(srcdir)/'`scripts/servers/sc_travelmaster.cpp

sc_default.lo: scripts/sc_default.cpp
	if $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT sc_default.lo -MD -MP -MF "$(DEPDIR)/sc_default.Tpo" -c -o sc_default.lo `test -f 'scripts/sc_default.cpp' || echo '$(srcdir)/'`scripts/sc_default.cpp; \
	then mv -f "$(DEPDIR)/sc_default.Tpo" "$(DEPDIR)/sc_default.Plo"; else rm -f "$(DEPDIR)/sc_default.Tpo"; exit 1; fi
#	source='scripts/sc_default.cpp' object='sc_default.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o sc_default.lo `test -f 'scripts/sc_default.cpp' || echo '$(srcdir)/'`scripts/sc_default.cpp

sc_defines.lo: scripts/sc_defines.cpp
	if $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT sc_defines.lo -MD -MP -MF "$(DEPDIR)/sc_defines.Tpo" -c -o sc_defines.lo `test -f 'scripts/sc_defines.cpp' || echo '$(srcdir)/'`scripts/sc_defines.cpp; \
	then mv -f "$(DEPDIR)/sc_defines.Tpo" "$(DEPDIR)/sc_defines.Plo"; else rm -f "$(DEPDIR)/sc_defines.Tpo"; exit 1; fi
#	source='scripts/sc_defines.cpp' object='sc_defines.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o sc_defines.lo `test -f 'scripts/sc_defines.cpp' || echo '$(srcdir)/'`scripts/sc_defines.cpp

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool
uninstall-info-am:

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	if test -z "$(ETAGS_ARGS)$$tags$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	    $$tags $$unique; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(CTAGS_ARGS)$$tags$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$tags $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	@srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's|.|.|g'`; \
	list='$(DISTFILES)'; for file in $$list; do \
	  case $$file in \
	    $(srcdir)/*) file=`echo "$$file" | sed "s|^$$srcdirstrip/||"`;; \
	    $(top_srcdir)/*) file=`echo "$$file" | sed "s|^$$topsrcdirstrip/|$(top_builddir)/|"`;; \
	  esac; \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
	  if test "$$dir" != "$$file" && test "$$dir" != "."; then \
	    dir="/$$dir"; \
	    $(mkdir_p) "$(distdir)$$dir"; \
	  else \
	    dir=''; \
	  fi; \
	  if test -d $$d/$$file; then \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -pR $(srcdir)/$$file $(distdir)$$dir || exit 1; \
	    fi; \
	    cp -pR $$d/$$file $(distdir)$$dir || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
check: check-am
all-am: Makefile $(LTLIBRARIES)
installdirs:
	for dir in "$(DESTDIR)$(libdir)"; do \
	  test -z "$$dir" || $(mkdir_p) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-generic clean-libLTLIBRARIES clean-libtool \
	mostlyclean-am

distclean: distclean-am
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

info: info-am

info-am:

install-data-am:

install-exec-am: install-libLTLIBRARIES

install-info: install-info-am

install-man:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-info-am uninstall-libLTLIBRARIES

.PHONY: CTAGS GTAGS all all-am check check-am clean clean-generic \
	clean-libLTLIBRARIES clean-libtool ctags distclean \
	distclean-compile distclean-generic distclean-libtool \
	distclean-tags distdir dvi dvi-am html html-am info info-am \
	install install-am install-data install-data-am install-exec \
	install-exec-am install-info install-info-am \
	install-libLTLIBRARIES install-man install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic mostlyclean-libtool pdf pdf-am ps ps-am \
	tags uninstall uninstall-am uninstall-info-am \
	uninstall-libLTLIBRARIES

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
