#ifndef DEF_ARCATRAZ_H
#define DEF_ARCATRAZ_H
#define DATA_DALLIAHTHEDOOMSAYEREVENT 1
#define DATA_HARBINGERSKYRISSEVENT 2
#define DATA_WRATH_SCRYERSOCCOTHRATESEVENT 3
#define DATA_ZEREKETHTHEUNBOUNDEVENT 4
#endif
