#ifndef DEF_STEAM_VAULT_H
#define DEF_STEAM_VAULT_H
#define DATA_HYDROMANCERTHESPIAEVENT 1
#define DATA_MEKGINEERSTEAMRIGGEREVENT 2
#define DATA_WARLORDKALITHRESHEVENT 3
#define DATA_NEARDISTILLER 4
#define DATA_MEKGINEERSTEAMRIGGER 5
#endif
