#ifndef DEF_HYJAL_H
#define DEF_HYJAL_H

#include "sc_instance.h"

#define DATA_ANETHERON 1
#define DATA_ANETHERONEVENT 2
#define DATA_ARCHIMONDE 3
#define DATA_ARCHIMONDEEVENT 4
#define DATA_AZGALOR 5
#define DATA_AZGALOREVENT 6
#define DATA_JAINAPROUDMOORE 7
#define DATA_KAZROGAL 8
#define DATA_KAZROGALEVENT 9
#define DATA_RAGEWINTERCHILL 10
#define DATA_RAGEWINTERCHILLEVENT 11
#define DATA_THRALL 12
#define DATA_TYRANDEWHISPERWIND 13

#endif
