#ifndef DEF_GRUULS_LAIR_H
#define DEF_GRUULS_LAIR_H
#define DATA_BLINDEYETHESEER 1
#define DATA_GRUULEVENT 2
#define DATA_KIGGLERTHECRAZED 3
#define DATA_KROSHFIREHAND 4
#define DATA_MAULGAREVENT 5
#define DATA_MAULGAREVENT_TANK 6
#define DATA_OLMTHESUMMONER 7
#endif
