#ifndef DEF_BLACK_TEMPLE_H
#define DEF_BLACK_TEMPLE_H
#define DATA_AKAMA 1
#define DATA_AKAMA_SHADE 2
#define DATA_GATHIOSTHESHATTERER 3
#define DATA_GURTOGGBLOODBOILEVENT 4
#define DATA_HIGHNETHERMANCERZEREVOR 5
#define DATA_HIGHWARLORDNAJENTUS 6
#define DATA_HIGHWARLORDNAJENTUSEVENT 7
#define DATA_ILLIDANSTORMRAGE 8
#define DATA_ILLIDANSTORMRAGEEVENT 9
#define DATA_ILLIDARICOUNCILEVENT 10
#define DATA_ILLIDARICOUNCIL 11
#define DATA_LADYMALANDE 12
#define DATA_MOTHERSHAHRAZEVENT 13
#define DATA_RELIQUARYOFSOULSEVENT 14
#define DATA_SHADEOFAKAMA 15
#define DATA_SHADEOFAKAMAEVENT 16
#define DATA_SUPREMUS 17
#define DATA_SUPREMUSEVENT 18
#define DATA_TERONGOREFIENDEVENT 19
#define DATA_VERASDARKSHADOW 20
#endif
