#ifndef DEF_TEMPLE_OF_AHNQIRAJ_H
#define DEF_TEMPLE_OF_AHNQIRAJ_H
#define DATA_SKERAM 1
#define DATA_KRI 2
#define DATA_VEM 3
#define DATA_VEMISDEAD 4
#define DATA_VEM_DEATH 5
#define DATA_VEKLOR 6
#define DATA_VEKLORISDEAD 7
#define DATA_VEKLOR_DEATH 8
#define DATA_VEKNILASH 9
#define DATA_VEKNILASHISDEAD 10
#define DATA_VEKNILASH_DEATH 11
#endif
