#ifndef DEF_ZULAMAN_H
#define DEF_ZULAMAN_H
#define DATA_JANALAI 1
#define DATA_JANALAIEVENT 2
#define DATA_J_EGGSLEFT 3
#define DATA_J_EGGSRIGHT 4
#define DATA_J_HATCHLEFT 5
#define DATA_J_HATCHRIGHT 6
#endif
