#ifndef DEF_THE_EYE_H
#define DEF_THE_EYE_H
#define DATA_ALAREVENT 1
#define DATA_ASTROMANCER 2
#define DATA_GRANDASTROMANCERCAPERNIAN 3
#define DATA_HIGHASTROMANCERSOLARIANEVENT 4
#define DATA_FATHOMLORDKARATHRESSEVENT 5
#define DATA_KAELTHAS 6
#define DATA_KAELTHASEVENT 7
#define DATA_LORDSANGUINAR 8
#define DATA_MASTERENGINEERTELONICUS 9
#define DATA_SOLARIANEVENT 10
#define DATA_THALADREDTHEDARKENER 11
#define DATA_VOIDREAVEREVENT 12
#endif
