#ifndef DEF_MAGTHERIDONS_LAIR_H
#define DEF_MAGTHERIDONS_LAIR_H
#define DATA_EVENT_STARTER 1
#define DATA_MAGTHERIDON 2
#define DATA_MAGTHERIDON_EVENT_ENDED 3
#define DATA_MAGTHERIDON_EVENT_STARTED 4
#define DATA_MAGTHERIDON_EVENT_STATUS 5
#endif
