#ifndef DEF_SERPENT_SHRINE_H
#define DEF_SERPENT_SHRINE_H

#include "sc_instance.h"

#define DATA_CANSTARTPHASE3 1
#define DATA_CARIBDIS 2
#define DATA_HYDROSSTHEUNSTABLEEVENT 3
#define DATA_KARATHRESS 4
#define DATA_KARATHRESSEVENT 5
#define DATA_KARATHRESSEVENT_STARTER 6
#define DATA_LADYVASHJ 7
#define DATA_LADYVASHJEVENT 8
#define DATA_LEOTHERASTHEBLINDEVENT 9
#define DATA_MOROGRIMTIDEWALKEREVENT 10
#define DATA_SHARKKIS 11
#define DATA_SHIELDGENERATOR1 12
#define DATA_SHIELDGENERATOR2 13
#define DATA_SHIELDGENERATOR3 14
#define DATA_SHIELDGENERATOR4 15
#define DATA_THELURKERBELOWEVENT 16
#define DATA_TIDALVESS 17
#define DATA_FATHOMLORDKARATHRESSEVENT 18
#endif
