UPDATE script_texts SET content_default='%s goes into a killing frenzy!' WHERE entry=-1000001;
UPDATE script_texts SET content_default='%s goes into a frenzy!' WHERE entry=-1000002;
UPDATE script_texts SET content_default='%s becomes enraged!' WHERE entry=-1000003;
UPDATE script_texts SET content_default='%s goes into a berserker rage!' WHERE entry=-1000004;
UPDATE script_texts SET content_default='%s hugs her father.' WHERE entry=-1000116;
UPDATE script_texts SET content_default='%s looks up at you quizzically. Maybe you should inspect it?' WHERE entry=-1000204;
UPDATE script_texts SET content_default='%s looks at you unexpectadly.' WHERE entry=-1000205;
UPDATE script_texts SET content_default='%s starts pecking at the feed.' WHERE entry=-1000206;
UPDATE script_texts SET content_default='Warning! %s emergency shutdown process initiated by $N. Shutdown will complete in two minutes.' WHERE entry=-1000211;
UPDATE script_texts SET content_default='%s begins tinkering with the goggles before the stone.' WHERE entry=-1000267;
UPDATE script_texts SET content_default='%s hands one glowing goggles over to Doctor Draxlegauge.' WHERE entry=-1000272;
UPDATE script_texts SET content_default='%s growls in acknowledgement before straightening and making her way off into the forest.' WHERE entry=-1000324;
UPDATE script_texts SET content_default='%s becomes enraged!' WHERE entry=-1189004;
UPDATE script_texts SET content_default='%s takes in a deep breath...' WHERE entry=-1249004;
UPDATE script_texts SET content_default='%s goes into a frenzy!' WHERE entry=-1269018;
UPDATE script_texts SET content_default='%s performs one last service for Ragnaros.' WHERE entry=-1409000;
UPDATE script_texts SET content_default='%s goes into a killing frenzy!' WHERE entry=-1409001;
UPDATE script_texts SET content_default='%s refuses to die while its master is in trouble.' WHERE entry=-1409002;
UPDATE script_texts SET content_default='%s goes into a killing frenzy!' WHERE entry=-1469002;
UPDATE script_texts SET content_default='%s flinches as its skin shimmers.' WHERE entry=-1469003;
UPDATE script_texts SET content_default='%s goes into a frenzy!' WHERE entry=-1469031;
UPDATE script_texts SET content_default='%s senses your fear.' WHERE entry=-1509000;
UPDATE script_texts SET content_default='%s bristles with energy!' WHERE entry=-1509001;
UPDATE script_texts SET content_default='%s sets eyes on $N!' WHERE entry=-1509002;
UPDATE script_texts SET content_default='%s is weakened!' WHERE entry=-1531011;
UPDATE script_texts SET content_default='%s begins to rust.' WHERE entry=-1532038;
UPDATE script_texts SET content_default='%s cries out in withdrawal, opening gates to the warp.' WHERE entry=-1532089;
UPDATE script_texts SET content_default='%s goes into a nether-fed rage!' WHERE entry=-1532090;
UPDATE script_texts SET content_default='%s goes into a berserker rage!' WHERE entry=-1533021;
UPDATE script_texts SET content_default='%s becomes enraged!' WHERE entry=-1533022;
UPDATE script_texts SET content_default='%s takes in a deep breath...' WHERE entry=-1533082;
UPDATE script_texts SET content_default='%s enrages!' WHERE entry=-1533083;
UPDATE script_texts SET content_default='%s enrages!' WHERE entry=-1540041;
UPDATE script_texts SET content_default='%s becomes enraged!' WHERE entry=-1544012;
UPDATE script_texts SET content_default='%s begins to cast Blast Nova!' WHERE entry=-1544013;
UPDATE script_texts SET content_default='%s\'s bonds begin to weaken!' WHERE entry=-1544014;
UPDATE script_texts SET content_default='%s breaks free!' WHERE entry=-1544015;
UPDATE script_texts SET content_default='%s sends his enemies to their watery graves!' WHERE entry=-1548039;
UPDATE script_texts SET content_default='%s summons Watery Globules!' WHERE entry=-1548041;
UPDATE script_texts SET content_default='%s sets his gaze on $N!' WHERE entry=-1550037;
UPDATE script_texts SET content_default='%s emits a strange noise.' WHERE entry=-1553006;
UPDATE script_texts SET content_default='%s draws energy from the air.' WHERE entry=-1555036;
UPDATE script_texts SET content_default='%s begins to channel arcane energy...' WHERE entry=-1556015;
UPDATE script_texts SET content_default='%s shifts into the void...' WHERE entry=-1557014;
UPDATE script_texts SET content_default='%s grows in size!' WHERE entry=-1565019;
UPDATE script_texts SET content_default='%s begins to channel from the nearby Fel Crystal...' WHERE entry=-1585006;
UPDATE script_texts SET content_default='%s discharges pure energy!' WHERE entry=-1585011;
UPDATE script_texts SET content_default='%s switches to Berserker Stance!' WHERE entry=-1602008;
UPDATE script_texts SET content_default='%s switches to Defensive Stance!' WHERE entry=-1602010;
UPDATE script_texts SET content_default='%s switches to Battle Stance!' WHERE entry=-1602006;
UPDATE script_texts SET content_default='%s begins to cast Lightning Nova!' WHERE entry=-1602031;
UPDATE script_texts SET content_default='%s runs to his anvil!' WHERE entry=-1602041;
UPDATE script_texts SET content_default='%s prepares to shatter his Brittle Golems!' WHERE entry=-1602042;
UPDATE script_texts SET content_default='%s dies from his wounds.' WHERE entry=-1609078;
UPDATE script_texts SET content_default='%s puts the shell to his ear.' WHERE entry=-1000185;
UPDATE script_texts SET content_default='%s kneels down and pick up the amulet.' WHERE entry=-1000197;
UPDATE script_texts SET content_default='%s raises his hammer menacingly...' WHERE entry=-1554012;
