#ifndef DEF_MOLTEN_CORE_H
#define DEF_MOLTEN_CORE_H

#include "sc_creature.h"
#include "sc_instance.h"

#define DATA_FLAMEWAKERPRIEST 1
#define DATA_GARRISDEAD 2
#define DATA_GEDDONISDEAD 3
#define DATA_GEHENNASISDEAD 4
#define DATA_GOLEMAGGISDEAD 5
#define DATA_GOLEMAGG_DEATH 6
#define DATA_LUCIFRONISDEAD 7
#define DATA_MAGMADARISDEAD 8
#define DATA_MAJORDOMOISDEAD 9
#define DATA_SHAZZRAHISDEAD 10
#define DATA_SULFURON 11
#define DATA_SULFURONISDEAD 12
#define DATA_GOLEMAGG 13
#endif
