#ifndef DEF_SCHOLOMANCE_H
#define DEF_SCHOLOMANCE_H

#include "sc_creature.h"
#include "sc_instance.h"

#define DATA_CANSPAWNGANDLING 1
#define DATA_DOCTORTHEOLENKRASTINOV_DEATH 2
#define DATA_INSTRUCTORMALICIA_DEATH 3
#define DATA_LADYILLUCIABAROV_DEATH 4
#define DATA_LORDALEXEIBAROV_DEATH 5
#define DATA_LOREKEEPERPOLKELT_DEATH 6
#define DATA_THERAVENIAN_DEATH 7
#endif
